name: badge_hack
description: A Flutter & Friends 2024 badge hack application.
publish_to: none

version: 0.0.1

environment:
  sdk: ^3.5.0

dependencies:
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  nfc_manager: ^3.5.0

dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
